#!/bin/bash
set -x
if [ -z "$2" ]; then
  echo "Usage: $(basename $0) outfile [prompt]"
  exit 1
fi

OUTFILE=$1
shift

set -e

cd $(dirname $0)

# Older torch required
. env/bin/activate

TMPDIR=$(mktemp -d)

python3 scripts/txt2img.py --n_iter 1 --n_samples 1 --plms --outdir ${TMPDIR} --prompt "$*"

# Now for upscaling
deactivate
cd ../Real-ESRGAN
. env/bin/activate

python inference_realesrgan.py --face_enhance -n RealESRGAN_x4plus -i ${TMPDIR}/samples/0000.png -o ${TMPDIR}

convert ${TMPDIR}/0000_out.png ${OUTFILE}

rm -rf ${TMPDIR}
